import { useState } from "react";
import Head from 'next/head'
import { useForm } from "react-hook-form";
import Users from "../public/temp-data"
export default function Home() {

  const { register, handleSubmit } = useForm();
  const [ErrorMessage, SetErrorMessage] = useState("");

  const onSubmit = (data) => {
    let {username, password} = data;
    if(
      Users.findIndex((el) =>{return el.username == username && el.password == password})+1
    ) {
      if(window.opener) {
        window.opener.postMessage(JSON.stringify(data), '*');
        window.close();
      } else {
        parent.postMessage(JSON.stringify(data), '*');
      }
    } else {
      SetErrorMessage("User not Found, Try again")
      console.log("ssdd")
    }
    
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit(onSubmit)}>
        <input {...register("username", { required: true })} placeholder="First name" value="mostafa"/>

        <input {...register("password", { minLength: 2 })} placeholder="Password" type="password" value="1234"/>

        <input type="submit" />
      </form>
    </>
  );
}
